/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelos.Registro;
import servicios.Conexion;
import servicios.Registro_servicio;

/**
 *
 * @author Ahri
 */
public class DlgIngresoRegistro extends javax.swing.JDialog {

    
      public static boolean isValidDate(String inDate) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    dateFormat.setLenient(false);
    try {
      dateFormat.parse(inDate.trim());
    } catch (Exception e) {
      return false;
    }
    return true;
  }
      
    /**
     * Creates new form DlgIngresoRegistro
     */
    public static String fechaActual() {
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatoFecha.format(fecha);
    }

    public DlgIngresoRegistro(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId_registro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFechaAA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        txtFechaMM = new javax.swing.JTextField();
        txtFechaDD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnFechaActual = new javax.swing.JButton();
        cmbMedida = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingreso de los registros");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("ID del registro");

        txtId_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_registroActionPerformed(evt);
            }
        });

        jLabel3.setText("Medicamento");

        jLabel4.setText("Fecha");

        txtFechaAA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaAA.setText("AAAA");
        txtFechaAA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaAAFocusGained(evt);
            }
        });
        txtFechaAA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaAAMouseClicked(evt);
            }
        });
        txtFechaAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaAAActionPerformed(evt);
            }
        });

        jLabel5.setText("Medida");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel6.setText("Stock");

        txtFechaMM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaMM.setText("MM");
        txtFechaMM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaMMFocusGained(evt);
            }
        });
        txtFechaMM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaMMMouseClicked(evt);
            }
        });

        txtFechaDD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaDD.setText("DD");
        txtFechaDD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaDDFocusGained(evt);
            }
        });
        txtFechaDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaDDMouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("/");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("/");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1446613046_floppy.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar registro");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1446609695_edit-clear.png"))); // NOI18N
        btnLimpiar.setToolTipText("Limpiar casillas de texto");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1446609011_go-back.png"))); // NOI18N
        btnVolver.setToolTipText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        btnFechaActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1447540901_calendar.png"))); // NOI18N
        btnFechaActual.setToolTipText("Insertar fecha actual");
        btnFechaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActualActionPerformed(evt);
            }
        });

        cmbMedida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione medida del medicamento", "sin medida", "100ml", "125ml", "250ml", "500ml", "1000ml" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtId_registro)
                    .addComponent(jScrollPane1)
                    .addComponent(txtStock, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFechaAA, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtFechaMM, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(txtFechaDD, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbMedida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaMM)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFechaActual)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFechaDD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFechaAA)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtId_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_registroActionPerformed

    private void txtFechaAAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaAAMouseClicked
        // TODO add your handling code here:
        txtFechaAA.setText(null);
        String vacio = "";
        if (txtFechaMM.getText().equals(vacio)) {
            txtFechaMM.setText("MM");
        }
        if (txtFechaDD.getText().equals(vacio)) {
            txtFechaDD.setText("DD");
        }
    }//GEN-LAST:event_txtFechaAAMouseClicked

    private void txtFechaMMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaMMMouseClicked
        // TODO add your handling code here:
        txtFechaMM.setText(null);
        String vacio = "";
        if (txtFechaAA.getText().equals(vacio)) {
            txtFechaAA.setText("AAAA");
        }
        if (txtFechaDD.getText().equals(vacio)) {
            txtFechaDD.setText("DD");
        }

    }//GEN-LAST:event_txtFechaMMMouseClicked

    private void txtFechaDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaDDMouseClicked
        // TODO add your handling code here:
        txtFechaDD.setText(null);
        txtFechaDD.setText(null);
        String vacio = "";
        if (txtFechaAA.getText().equals(vacio)) {
            txtFechaAA.setText("AAAA");
        }
        if (txtFechaMM.getText().equals(vacio)) {
            txtFechaMM.setText("MM");
        }

    }//GEN-LAST:event_txtFechaDDMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        

// TODO add your handling code here:
        
        
        
        Registro registro = new Registro();
        Registro_servicio rs = new Registro_servicio();
        Conexion con = new Conexion();
        Connection reg = con.obtenerConexion();
        int id_registro, stock, aux = 0;
        String nombre, fecha, medida;
        id_registro = Integer.parseInt(txtId_registro.getText());
        nombre = txtDescripcion.getText();
        fecha = txtFechaAA.getText() + "-" + txtFechaMM.getText() + "-" + txtFechaDD.getText();
        medida = cmbMedida.getSelectedItem().toString();
        stock = Integer.parseInt(txtStock.getText());
        registro = new Registro(id_registro, nombre, fecha, medida, stock);
        
        String aux5 = txtId_registro.getText().trim();
        String aux2 = txtDescripcion.getText().trim();
        String ano = txtFechaAA.getText().trim();
        String mes = txtFechaMM.getText().trim();
        String dia = txtFechaDD.getText().trim();
        String aux13 = cmbMedida.getSelectedItem().toString();
        String aux15 = txtStock.getText();
        String ano1 = txtFechaAA.getText();
        String mes1 = txtFechaMM.getText();
        String dia1= txtFechaDD.getText();

        String fechas = ano1+'-'+mes1+'-'+dia1;
        
        if (isValidDate(fechas)) {
     
            if(aux13== "Seleccione medida del medicamento"||aux5.length()== 0||aux2.length()== 0||ano.length()== 0||dia.length()== 0||mes.length()== 0||aux15.length()== 0){
                JOptionPane.showMessageDialog(this,"Cada campo debe ser llenado","Error",JOptionPane.ERROR_MESSAGE);
            }else{
        
        try {
            PreparedStatement consulta = reg.prepareStatement("SELECT * FROM registro");
            ResultSet resultado = consulta.executeQuery();
            while (resultado.next()) {
                if (resultado.getInt("id_registro") == id_registro) {
                    aux=1;
                } else {
                    if (resultado.getString("nombre").equals(nombre) && resultado.getString("medida").equals(medida)) {
                        aux = 2;
                    }
                }
            }
        } catch (SQLException ex) {

        }
        if (aux == 0) {
            rs.guardar(reg, registro);
            JOptionPane.showMessageDialog(this, "Se guardo su registro correctamente");
            this.setVisible(false);
        } else {
            if(aux==2){
            JOptionPane.showMessageDialog(this, "Ya se encuentra el NOMBRE y MEDIDA del medicamento registrado en nuestras bases de datos");
            cmbMedida.setSelectedItem("Seleccione medida del medicamento");
            cmbMedida.requestFocus();}else{
                if(aux==1){
                   JOptionPane.showMessageDialog(this, "Ya se encuentra el CODIGO del medicamento registrado en nuestras bases de datos");
                   txtId_registro.setText(null);
                   txtId_registro.requestFocus();
                }
            }
        }
        }}else{JOptionPane.showMessageDialog(this,"Error en la fecha","Error",JOptionPane.ERROR_MESSAGE); }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtFechaAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaAAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaAAActionPerformed

    private void txtFechaAAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaAAFocusGained
        // TODO add your handling code here:
        txtFechaAA.setText(null);
        String vacio = "";
        if (txtFechaMM.getText().equals(vacio)) {
            txtFechaMM.setText("MM");
        }
        if (txtFechaDD.getText().equals(vacio)) {
            txtFechaDD.setText("DD");
        }
    }//GEN-LAST:event_txtFechaAAFocusGained

    private void txtFechaMMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaMMFocusGained
        // TODO add your handling code here:
        txtFechaMM.setText(null);
        String vacio = "";
        if (txtFechaAA.getText().equals(vacio)) {
            txtFechaAA.setText("AAAA");
        }
        if (txtFechaDD.getText().equals(vacio)) {
            txtFechaDD.setText("DD");
        }

    }//GEN-LAST:event_txtFechaMMFocusGained

    private void txtFechaDDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaDDFocusGained
        // TODO add your handling code here:
        txtFechaDD.setText(null);
        String vacio = "";
        if (txtFechaAA.getText().equals(vacio)) {
            txtFechaAA.setText("AAAA");
        }
        if (txtFechaMM.getText().equals(vacio)) {
            txtFechaMM.setText("MM");
        }

    }//GEN-LAST:event_txtFechaDDFocusGained

    private void btnFechaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActualActionPerformed
        // TODO add your handling code here:
        String[] fecha = fechaActual().split("/");
        txtFechaDD.setText(fecha[0]);
        txtFechaMM.setText(fecha[1]);
        txtFechaAA.setText(fecha[2]);
    }//GEN-LAST:event_btnFechaActualActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtId_registro.setText(null);
        txtDescripcion.setText(null);
        cmbMedida.setSelectedItem("Seleccione medida del medicamento");
        txtStock.setText(null);
        txtId_registro.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgIngresoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgIngresoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgIngresoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgIngresoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgIngresoRegistro dialog = new DlgIngresoRegistro(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechaActual;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox cmbMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFechaAA;
    private javax.swing.JTextField txtFechaDD;
    private javax.swing.JTextField txtFechaMM;
    private javax.swing.JTextField txtId_registro;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
