/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelos;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servicios.Conexion;
import servicios.Registro_servicio;

/**
 *
 * @author Ahri
 */
public class DlgManejoUsuario extends javax.swing.JDialog {

    /**
     * Creates new form DlgManejoUsuario1
     */
    void borrarTabla() {
        int nroFilas = 0;
        DefaultTableModel modeloDeMiTabla = (DefaultTableModel) tbUsuario.getModel();
        modeloDeMiTabla.addRow(new Object[nroFilas]);
        for (nroFilas = 0; nroFilas < 100; nroFilas++) {
            tbUsuario.setValueAt(false, nroFilas, 0);
            tbUsuario.setValueAt(null, nroFilas, 1);
            tbUsuario.setValueAt(null, nroFilas, 2);
            tbUsuario.setValueAt(null, nroFilas, 3);
            tbUsuario.setValueAt(null, nroFilas, 4);
            tbUsuario.setValueAt(null, nroFilas, 5);
            tbUsuario.setValueAt(null, nroFilas, 6);
        }

    }

    public DlgManejoUsuario(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        int nroFilas = 0;
        DefaultTableModel modeloDeMiTabla = (DefaultTableModel) tbUsuario.getModel();
        modeloDeMiTabla.addRow(new Object[nroFilas]);
        Registro_servicio rs = new Registro_servicio();
        Conexion con = new Conexion();
        Connection reg = con.obtenerConexion();
        try {
            PreparedStatement consulta = reg.prepareStatement("SELECT * FROM usuario");
            ResultSet resultado = consulta.executeQuery();
            while (resultado.next()) {
                tbUsuario.setValueAt(false, nroFilas, 0);
                tbUsuario.setValueAt(resultado.getString("nick_usuario"), nroFilas, 1);
                tbUsuario.setValueAt(resultado.getString("nombre"), nroFilas, 2);
                tbUsuario.setValueAt(resultado.getString("apellidos"), nroFilas, 3);
                tbUsuario.setValueAt(resultado.getString("cargo_administrativo"), nroFilas, 4);
                tbUsuario.setValueAt(resultado.getString("pregunta_seguridad"), nroFilas, 5);
                tbUsuario.setValueAt(resultado.getString("unidad"), nroFilas, 6);
                nroFilas++;
            }
            consulta.close();
        } catch (SQLException ex) {
            Logger.getLogger(Registro_servicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        nroFilas = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnIngresarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnModificarUsuario = new javax.swing.JButton();
        btnActualizarTabla = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuario = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cmbBusqueda = new javax.swing.JComboBox();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manejo datos de usuario");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnIngresarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1447384334_kuser.png"))); // NOI18N
        btnIngresarUsuario.setToolTipText("Ingresar usuario");
        btnIngresarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarUsuarioActionPerformed(evt);
            }
        });

        btnEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1446604726_trash.png"))); // NOI18N
        btnEliminarUsuario.setToolTipText("Eliminar usuario");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        btnModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1446604054_Notes.png"))); // NOI18N
        btnModificarUsuario.setToolTipText("Modificar usuario");
        btnModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuarioActionPerformed(evt);
            }
        });

        btnActualizarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1446607608_adept_update.png"))); // NOI18N
        btnActualizarTabla.setToolTipText("Carga la base de datos");
        btnActualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTablaActionPerformed(evt);
            }
        });

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1446609011_go-back.png"))); // NOI18N
        btnVolver.setToolTipText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIngresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Usuario"));

        tbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Usuario", "Nombre", "Apellidos", "Cargo", "Pregunta Seguridad", "Unidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbUsuario);
        if (tbUsuario.getColumnModel().getColumnCount() > 0) {
            tbUsuario.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbUsuario.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Busqueda por..."));

        cmbBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un dato del usuario", "Nombre de usuario", "Nombre", "Apellidos", "Cargo administrativo" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1447384412_folder-search.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnIngresarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarUsuarioActionPerformed
        // TODO add your handling code here:
        DlgIngresarUsuario diu = new DlgIngresarUsuario(new javax.swing.JDialog(), true);
        diu.setVisible(true);
        diu.dispose();
    }//GEN-LAST:event_btnIngresarUsuarioActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        // TODO add your handling code here:
        int resp=JOptionPane.showConfirmDialog(this,"Seguro que desea Eliminar datos del registro de bodega?","Confirma",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(resp==JOptionPane.OK_OPTION){
        Conexion con = new Conexion();
        Connection reg = con.obtenerConexion();
        String usuario;
        try {
            for (int i = 0; i < tbUsuario.getRowCount(); i++) {
                boolean a = Boolean.parseBoolean(tbUsuario.getValueAt(i, 0).toString());
                if (a == true) {
                    usuario = tbUsuario.getValueAt(i, 1).toString();
                    try {
                        PreparedStatement consulta = reg.prepareStatement("DELETE FROM usuario WHERE nick_usuario = ?");
                        consulta.setString(1, usuario);
                        consulta.execute();
                    } catch (SQLException ex) {
                    }
                }
            }
        } catch (Exception ex) {

        }}
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuarioActionPerformed
        // TODO add your handling code here:
        int contador = 0, fila = 0;
        String usuario;
        String aux = "";
        try {
            for (int i = 0; i < tbUsuario.getRowCount(); i++) {
                boolean a = Boolean.parseBoolean(tbUsuario.getValueAt(i, 0).toString());
                if (a == true) {
                    contador++;
                    fila = i;
                }
            }
        } catch (Exception ex) {

        }
        if (tbUsuario.getValueAt(fila, 4).toString().equals("total")) {
            aux = "no modificar administrador total";
        }
        if (aux.equals("no modificar administrador total")) {
            JOptionPane.showMessageDialog(this, "No puede modificar datos del administrador con cargo 'total'");
        } else {
            if (contador > 1) {
                JOptionPane.showMessageDialog(this, "Porfavor, seleccione un solo item para modificar");
            } else {
                if (contador == 0) {
                    JOptionPane.showMessageDialog(this, "Porfavor, seleccione un item a modificar");
                } else {
                    if (contador == 1) {
                        usuario = tbUsuario.getValueAt(fila, 1).toString();
                        try {
                            FileWriter f = new FileWriter("guardarValor.txt");
                            PrintWriter pf = new PrintWriter(f);
                            pf.println(usuario);
                            pf.close();
                        } catch (Exception ex) {
                        }
                        DlgModificacionUsuario dimod = new DlgModificacionUsuario(new javax.swing.JDialog(), true);
                        dimod.setVisible(true);
                        dimod.dispose();
                    }
                }
            }
        }

    }//GEN-LAST:event_btnModificarUsuarioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Conexion con = new Conexion();
        Connection reg = con.obtenerConexion();
        String busqueda = (String) cmbBusqueda.getSelectedItem();
        if (busqueda.equals("Nombre de usuario")) {
            borrarTabla();
            int nroFilas = 0;
            DefaultTableModel modeloDeMiTabla = (DefaultTableModel) tbUsuario.getModel();
            modeloDeMiTabla.addRow(new Object[nroFilas]);
            try {
                PreparedStatement consulta = reg.prepareStatement("SELECT * FROM usuario");
                ResultSet resultado = consulta.executeQuery();
                while (resultado.next()) {
                    if (resultado.getString("nick_usuario").equals(txtBusqueda.getText())) {
                        tbUsuario.setValueAt(false, nroFilas, 0);
                        tbUsuario.setValueAt(resultado.getString("nick_usuario"), nroFilas, 1);
                        tbUsuario.setValueAt(resultado.getString("nombre"), nroFilas, 2);
                        tbUsuario.setValueAt(resultado.getString("apellidos"), nroFilas, 3);
                        tbUsuario.setValueAt(resultado.getString("cargo_administrativo"), nroFilas, 4);
                        tbUsuario.setValueAt(resultado.getString("pregunta_seguridad"), nroFilas, 5);
                        tbUsuario.setValueAt(resultado.getString("unidad"), nroFilas, 6);
                        nroFilas++;
                    }
                }
            } catch (SQLException ex) {
                System.out.printf("No hace nada");
            }
        } else {
            if (busqueda.equals("Nombre")) {
                borrarTabla();
                int nroFilas = 0;
                DefaultTableModel modeloDeMiTabla = (DefaultTableModel) tbUsuario.getModel();
                modeloDeMiTabla.addRow(new Object[nroFilas]);
                try {
                    PreparedStatement consulta = reg.prepareStatement("SELECT * FROM usuario ");
                    ResultSet resultado = consulta.executeQuery();
                    while (resultado.next()) {
                        if (resultado.getString("nombre").equals(txtBusqueda.getText())) {
                            tbUsuario.setValueAt(false, nroFilas, 0);
                            tbUsuario.setValueAt(resultado.getString("nick_usuario"), nroFilas, 1);
                            tbUsuario.setValueAt(resultado.getString("nombre"), nroFilas, 2);
                            tbUsuario.setValueAt(resultado.getString("apellidos"), nroFilas, 3);
                            tbUsuario.setValueAt(resultado.getString("cargo_administrativo"), nroFilas, 4);
                            tbUsuario.setValueAt(resultado.getString("pregunta_seguridad"), nroFilas, 5);
                            tbUsuario.setValueAt(resultado.getString("unidad"), nroFilas, 6);
                            nroFilas++;
                        }
                    }
                } catch (SQLException ex) {
                    System.out.printf("No hace nada");
                }
            } else {
                if (busqueda.equals("Apellidos")) {
                    borrarTabla();
                    int nroFilas = 0;
                    DefaultTableModel modeloDeMiTabla = (DefaultTableModel) tbUsuario.getModel();
                    modeloDeMiTabla.addRow(new Object[nroFilas]);
                    try {
                        PreparedStatement consulta = reg.prepareStatement("SELECT * FROM usuario");
                        ResultSet resultado = consulta.executeQuery();
                        while (resultado.next()) {
                            if (resultado.getString("apellidos").equals(txtBusqueda.getText())) {
                                tbUsuario.setValueAt(false, nroFilas, 0);
                                tbUsuario.setValueAt(resultado.getString("nick_usuario"), nroFilas, 1);
                                tbUsuario.setValueAt(resultado.getString("nombre"), nroFilas, 2);
                                tbUsuario.setValueAt(resultado.getString("apellidos"), nroFilas, 3);
                                tbUsuario.setValueAt(resultado.getString("cargo_administrativo"), nroFilas, 4);
                                tbUsuario.setValueAt(resultado.getString("pregunta_seguridad"), nroFilas, 5);
                                tbUsuario.setValueAt(resultado.getString("unidad"), nroFilas, 6);
                                nroFilas++;
                            }
                        }
                    } catch (SQLException ex) {
                        System.out.printf("No hace nada");
                    }
                } else {
                    if (busqueda.equals("Cargo administrativo")) {
                        borrarTabla();
                        int nroFilas = 0;
                        DefaultTableModel modeloDeMiTabla = (DefaultTableModel) tbUsuario.getModel();
                        modeloDeMiTabla.addRow(new Object[nroFilas]);
                        try {
                            PreparedStatement consulta = reg.prepareStatement("SELECT * FROM usuario");
                            ResultSet resultado = consulta.executeQuery();
                            while (resultado.next()) {
                                if (resultado.getString("cargo_administrativo").equals(txtBusqueda.getText())) {
                                    tbUsuario.setValueAt(false, nroFilas, 0);
                                    tbUsuario.setValueAt(resultado.getString("nick_usuario"), nroFilas, 1);
                                    tbUsuario.setValueAt(resultado.getString("nombre"), nroFilas, 2);
                                    tbUsuario.setValueAt(resultado.getString("apellidos"), nroFilas, 3);
                                    tbUsuario.setValueAt(resultado.getString("cargo_administrativo"), nroFilas, 4);
                                    tbUsuario.setValueAt(resultado.getString("pregunta_seguridad"), nroFilas, 5);
                                    tbUsuario.setValueAt(resultado.getString("unidad"), nroFilas, 6);
                                    nroFilas++;
                                }
                            }
                        } catch (SQLException ex) {
                            System.out.printf("No hace nada");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Error, Seleccione un dato de usuario");
                    }
                }
            }
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTablaActionPerformed
        // TODO add your handling code here:
        borrarTabla();
        int nroFilas = 0;
        DefaultTableModel modeloDeMiTabla = (DefaultTableModel) tbUsuario.getModel();
        modeloDeMiTabla.addRow(new Object[nroFilas]);
        Registro_servicio rs = new Registro_servicio();
        Conexion con = new Conexion();
        Connection reg = con.obtenerConexion();
        try {
            PreparedStatement consulta = reg.prepareStatement("SELECT * FROM usuario");
            ResultSet resultado = consulta.executeQuery();
            while (resultado.next()) {
                tbUsuario.setValueAt(false, nroFilas, 0);
                tbUsuario.setValueAt(resultado.getString("nick_usuario"), nroFilas, 1);
                tbUsuario.setValueAt(resultado.getString("nombre"), nroFilas, 2);
                tbUsuario.setValueAt(resultado.getString("apellidos"), nroFilas, 3);
                tbUsuario.setValueAt(resultado.getString("cargo_administrativo"), nroFilas, 4);
                tbUsuario.setValueAt(resultado.getString("pregunta_seguridad"), nroFilas, 5);
                tbUsuario.setValueAt(resultado.getString("unidad"), nroFilas, 6);
                nroFilas++;
            }
            consulta.close();
        } catch (SQLException ex) {
            Logger.getLogger(Registro_servicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        nroFilas = 0;
    }//GEN-LAST:event_btnActualizarTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgManejoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgManejoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgManejoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgManejoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgManejoUsuario dialog = new DlgManejoUsuario(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTabla;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnIngresarUsuario;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox cmbBusqueda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbUsuario;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
