/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tareasimulacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Ahri
 */

public class Buffon extends javax.swing.JFrame {
int cortesEjeY[]=new int[21];
int auxiliar=0,contadorCorte=0,contadorTotal=0,sinCorte=0,activo=0;
    /**
     * Creates new form Buffon
     */
    public Buffon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDibujo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnHacerLineasParalelas = new javax.swing.JButton();
        btnHacerRecta = new javax.swing.JButton();
        btnHacerRectas = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlDibujoLayout = new javax.swing.GroupLayout(pnlDibujo);
        pnlDibujo.setLayout(pnlDibujoLayout);
        pnlDibujoLayout.setHorizontalGroup(
            pnlDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        pnlDibujoLayout.setVerticalGroup(
            pnlDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        btnHacerLineasParalelas.setText("hacerLineasParalelas");
        btnHacerLineasParalelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHacerLineasParalelasMouseClicked(evt);
            }
        });
        btnHacerLineasParalelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHacerLineasParalelasActionPerformed(evt);
            }
        });

        btnHacerRecta.setText("hacerRecta");
        btnHacerRecta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHacerRectaMouseClicked(evt);
            }
        });

        btnHacerRectas.setText("hacerRectas");
        btnHacerRectas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHacerRectasMouseClicked(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        btnMostrar.setText("mostrarResultado");
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHacerLineasParalelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHacerRecta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHacerRectas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHacerLineasParalelas)
                    .addComponent(btnHacerRecta)
                    .addComponent(btnHacerRectas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnMostrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        btnSalir.setText("Salir de programa");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHacerLineasParalelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerLineasParalelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHacerLineasParalelasActionPerformed

    private void btnHacerLineasParalelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHacerLineasParalelasMouseClicked
        // TODO add your handling code here:
        activo=1;
        int aux=0;
        while(aux<=400){
        Dibujo.hacerRectasParalelas(pnlDibujo.getGraphics(),0,aux,400);
        cortesEjeY[auxiliar]=aux;
        auxiliar++;
        aux=aux+20;
        }
        auxiliar=0;
    }//GEN-LAST:event_btnHacerLineasParalelasMouseClicked

    private void btnHacerRectaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHacerRectaMouseClicked
        // TODO add your handling code here:
        double nAleatorio1,nAleatorio2,nAleatorio3,nAleatorio4;
        int nAleatorioEntero1,nAleatorioEntero2,nAleatorioEntero3,nAleatorioEntero4,aux,aux2=0,y1,y2;
        int m,n=0;
        if(activo==1){
        while(aux2==0){
            
        nAleatorio1= (Math.random() * 400) + 0;
        nAleatorioEntero1 = (int) nAleatorio1;
        nAleatorio2 = (Math.random() * 400) + 0;
        nAleatorioEntero2 = (int) nAleatorio2;
        nAleatorio3 = (Math.random() * 400) + 0;
        nAleatorioEntero3 = (int) nAleatorio3;
        nAleatorio4= (Math.random() * 400) + 0;
        nAleatorioEntero4 = (int) nAleatorio4;
       
        aux=(nAleatorioEntero3-nAleatorioEntero1)*(nAleatorioEntero3-nAleatorioEntero1)+(nAleatorioEntero4-nAleatorioEntero2)*(nAleatorioEntero4-nAleatorioEntero2);
            if(aux==400){       
                 //y2 es mayor a y1
                 if(nAleatorioEntero2<nAleatorioEntero4){
                    y1=nAleatorioEntero2;
                    y2=nAleatorioEntero4;
                 }   
                    else{
                        y2=nAleatorioEntero2;
                        y1=nAleatorioEntero4;
                    }
                m=y2;
                //Esto ve cuales lineas se intersectan
                while(auxiliar<21  && n==0){
                    while(y2>y1 && n==0){
                        if(y2==cortesEjeY[auxiliar]){
                            contadorCorte++;
                            sinCorte=1;
                            n=1;
                        }
                        y2--;
                    } 
                    auxiliar++;
                    y2=m;
                }
                auxiliar=0;
                Dibujo.hacerRecta(pnlDibujo.getGraphics(),nAleatorioEntero1,nAleatorioEntero2,nAleatorioEntero3,nAleatorioEntero4,sinCorte);
                aux2=1;
                contadorTotal++;
                sinCorte=0;
            }
         }
        }else{
            JOptionPane.showMessageDialog(this,"Dibuja lineas paralelas, si no no puede trazar lineas.");
            JOptionPane.showMessageDialog(this," Se reinician los valores");
            pnlDibujo.repaint();
            activo=0;
        }
    }//GEN-LAST:event_btnHacerRectaMouseClicked

    private void btnHacerRectasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHacerRectasMouseClicked
        // TODO add your handling code here:
        double nAleatorio1,nAleatorio2,nAleatorio3,nAleatorio4;
        int nAleatorioEntero1,nAleatorioEntero2,nAleatorioEntero3,nAleatorioEntero4,aux,aux2=0,aux3=0;
        int y1,y2,m,n=0;
        if(activo==1){
        while(aux3<1000){
        while(aux2==0){
        nAleatorio1= (Math.random() * 400) + 0;
        nAleatorioEntero1 = (int) nAleatorio1;
        nAleatorio2 = (Math.random() * 400) + 0;
        nAleatorioEntero2 = (int) nAleatorio2;
        nAleatorio3 = (Math.random() * 400) + 0;
        nAleatorioEntero3 = (int) nAleatorio3;
        nAleatorio4= (Math.random() * 400) + 0;
        nAleatorioEntero4 = (int) nAleatorio4;
        
        aux=(nAleatorioEntero3-nAleatorioEntero1)*(nAleatorioEntero3-nAleatorioEntero1)+(nAleatorioEntero4-nAleatorioEntero2)*(nAleatorioEntero4-nAleatorioEntero2);
            if(aux==400){       
                //y2 es mayor a y1
                 if(nAleatorioEntero2<nAleatorioEntero4){
                    y1=nAleatorioEntero2;
                    y2=nAleatorioEntero4;
                 }   
                    else{
                        y2=nAleatorioEntero2;
                        y1=nAleatorioEntero4;
                    }
                m=y2;
                //Esto ve cuales lineas se intersectan
                while(auxiliar<21  && n==0){
                    while(y2>y1 && n==0){
                        if(y2==cortesEjeY[auxiliar]){
                            contadorCorte++;
                            sinCorte=1;
                            n=1;
                        }
                        y2--;
                    } 
                    auxiliar++;
                    y2=m;
                }
                auxiliar=0;
                n=0;
                Dibujo.hacerRecta(pnlDibujo.getGraphics(),nAleatorioEntero1,nAleatorioEntero2,nAleatorioEntero3,nAleatorioEntero4,sinCorte);
                aux2=1;
                contadorTotal++;
                sinCorte=0;
                
            }
         }
        aux2=0;
        aux3++;
        }
    }
      else{
            JOptionPane.showMessageDialog(this,"Dibuja lineas paralelas, si no no puede trazar lineas.");
            JOptionPane.showMessageDialog(this," Se reinician los valores");
            pnlDibujo.repaint();
            activo=0;
        }  
    }//GEN-LAST:event_btnHacerRectasMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
         pnlDibujo.repaint();
         activo=0;
         contadorCorte=0;
         contadorTotal=0;
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseClicked
        // TODO add your handling code here
        float aux1,aux2,aux3;
        aux1=(float)contadorTotal;
        aux2=(float)contadorCorte;
        aux3=2*aux1/aux2;
        JOptionPane.showMessageDialog(this,aux3);
        JOptionPane.showMessageDialog(this," Se reinician los valores");
        pnlDibujo.repaint();
        aux3=0;
        activo=0;
        contadorCorte=0;
         contadorTotal=0;
    }//GEN-LAST:event_btnMostrarMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         int resp=JOptionPane.showConfirmDialog(this,"Seguro que desea salir del programa?","Confirma",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(resp==JOptionPane.OK_OPTION){
            JOptionPane.showMessageDialog(this,"Gracias por usar este programa");
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buffon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buffon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buffon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buffon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buffon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHacerLineasParalelas;
    private javax.swing.JButton btnHacerRecta;
    private javax.swing.JButton btnHacerRectas;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlDibujo;
    // End of variables declaration//GEN-END:variables
}
