/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tareasimulacion;

import javax.swing.JOptionPane;


/**
 *
 * @author Ahri
 */
public class DeMonteCarlo extends javax.swing.JFrame {
    /**
     * Creates new form DeMonteCarlo
     */
    int contadorTotal=0,contadorCirculo=0,activoCirculo=0,activoCuadrado=0,sinCorte=0;
    public DeMonteCarlo() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDibujo = new javax.swing.JPanel();
        pnlPanelBotones = new javax.swing.JPanel();
        btnHacerCuadrado = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnHacerCircunferencia = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCrearPuntos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnbFile = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlDibujoLayout = new javax.swing.GroupLayout(pnlDibujo);
        pnlDibujo.setLayout(pnlDibujoLayout);
        pnlDibujoLayout.setHorizontalGroup(
            pnlDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        pnlDibujoLayout.setVerticalGroup(
            pnlDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        btnHacerCuadrado.setText("hacerCuadrado");
        btnHacerCuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHacerCuadradoMouseClicked(evt);
            }
        });

        btnMostrar.setText("mostrarResultado");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnHacerCircunferencia.setText("hacerCircunferencia");
        btnHacerCircunferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHacerCircunferenciaMouseClicked(evt);
            }
        });

        btnPunto.setText("crearUnPunto");
        btnPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPuntoMouseClicked(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        btnCrearPuntos.setText("crearPuntos");
        btnCrearPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPuntosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPanelBotonesLayout = new javax.swing.GroupLayout(pnlPanelBotones);
        pnlPanelBotones.setLayout(pnlPanelBotonesLayout);
        pnlPanelBotonesLayout.setHorizontalGroup(
            pnlPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelBotonesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHacerCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelBotonesLayout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPanelBotonesLayout.createSequentialGroup()
                        .addComponent(btnHacerCircunferencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlPanelBotonesLayout.setVerticalGroup(
            pnlPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHacerCuadrado)
                    .addComponent(btnHacerCircunferencia)
                    .addComponent(btnPunto))
                .addGap(20, 20, 20)
                .addGroup(pnlPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCrearPuntos))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        mnbFile.setText("File");

        mnSalir.setText("Salir del programa");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mnbFile.add(mnSalir);

        jMenuBar1.add(mnbFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHacerCuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHacerCuadradoMouseClicked
        // TODO add your handling code here:
         Dibujo.hacerCuadrado(pnlDibujo.getGraphics(),0,0,400);
         activoCuadrado=1;
    }//GEN-LAST:event_btnHacerCuadradoMouseClicked

    private void btnHacerCircunferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHacerCircunferenciaMouseClicked
        // TODO add your handling code here:
        activoCirculo=1;
        Dibujo.hacerCircunferencia(pnlDibujo.getGraphics(),0,0,400,400);
    }//GEN-LAST:event_btnHacerCircunferenciaMouseClicked

    private void btnPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPuntoMouseClicked
        // TODO add your handling code here:
        if(activoCirculo==1 && activoCuadrado==1){
        double nAleatorio1 = (Math.random() * 400) + 0;
        int nAleatorioEntero1 = (int) nAleatorio1;
        double nAleatorio2 = (Math.random() * 400) + 0;
        int nAleatorioEntero2 = (int) nAleatorio2;
        if(Dibujo.contarPuntosCirculo(nAleatorioEntero1, nAleatorioEntero2)==1){
                contadorCirculo++;
                sinCorte=1;
        }
        Dibujo.hacerPunto(pnlDibujo.getGraphics(), nAleatorioEntero1, nAleatorioEntero2,sinCorte);
        contadorTotal++;
        sinCorte=0;    
        }else{
        JOptionPane.showMessageDialog(this,"Dibuja la circunferencia y/o cuadrado, ya que no se generan puntos sin ambas estas figuras.");
        JOptionPane.showMessageDialog(this," Se reinician los valores");
        pnlDibujo.repaint();
        activoCirculo=0;
        activoCuadrado=0;
        
        }     
        
        
    }//GEN-LAST:event_btnPuntoMouseClicked

    private void btnCrearPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPuntosActionPerformed
        // TODO add your handling code here:
        if(activoCirculo==1 && activoCuadrado==1){
        double nAleatorio1,nAleatorio2;
        int nAleatorioEntero1,nAleatorioEntero2,aux=0;
        while(aux<1000){
        nAleatorio1 = (Math.random() * 400) + 0;
        nAleatorioEntero1 = (int) nAleatorio1;
        nAleatorio2 = (Math.random() * 400) + 0;
        nAleatorioEntero2 = (int) nAleatorio2;
             if(Dibujo.contarPuntosCirculo(nAleatorioEntero1, nAleatorioEntero2)==1){
                contadorCirculo++;
                sinCorte=1;
            }
        Dibujo.hacerPunto(pnlDibujo.getGraphics(), nAleatorioEntero1, nAleatorioEntero2,sinCorte);
        aux++;
        contadorTotal++;
        sinCorte=0;    
        }
    }else{
        JOptionPane.showMessageDialog(this,"Dibuja la circunferencia y/o cuadrado, ya que no se generan "
                + "puntos sin ambas estas figuras.");
        JOptionPane.showMessageDialog(this," Se reinician los valores");
        pnlDibujo.repaint();
        activoCirculo=0;
        activoCuadrado=0;
        
        } 
    }//GEN-LAST:event_btnCrearPuntosActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        float resultado;
        float resultado1=(float)(4*contadorCirculo);
        float resultado2=(float)contadorTotal;
        resultado=resultado1/resultado2;
        
        JOptionPane.showMessageDialog(this,"pi="+resultado);
        JOptionPane.showMessageDialog(this," Se reinician los valores");
        pnlDibujo.repaint();
        activoCirculo=0;
        activoCuadrado=0;
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
        pnlDibujo.repaint();
        contadorTotal=0;
        contadorCirculo=0;
        activoCirculo=0;
        activoCuadrado=0;
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        // TODO add your handling code here:
        int resp=JOptionPane.showConfirmDialog(this,"Seguro que desea salir del programa?","Confirma",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(resp==JOptionPane.OK_OPTION){
            JOptionPane.showMessageDialog(this,"Gracias por usar este programa");
            System.exit(0);
        }
    }//GEN-LAST:event_mnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeMonteCarlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeMonteCarlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeMonteCarlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeMonteCarlo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeMonteCarlo().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPuntos;
    private javax.swing.JButton btnHacerCircunferencia;
    private javax.swing.JButton btnHacerCuadrado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnPunto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenu mnbFile;
    private javax.swing.JPanel pnlDibujo;
    private javax.swing.JPanel pnlPanelBotones;
    // End of variables declaration//GEN-END:variables
}
